//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll_Mvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public int User_id { get; set; }
        public string User_Name { get; set; }
        public Nullable<System.DateTime> Joined_on { get; set; }
        public Nullable<int> Age { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}
