//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll_Mvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveEmp
    {
        public int id { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<System.DateTime> StartLeave { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public Nullable<int> Numoffdays { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> Applydate { get; set; }
        public Nullable<System.DateTime> Leavedate { get; set; }
        public string Approved { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
