//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll_Mvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class salaryreport
    {
        public int id { get; set; }
        public Nullable<int> User_id { get; set; }
        public string User_Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Month { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<double> PfAmount { get; set; }
        public Nullable<double> Esi { get; set; }
        public Nullable<double> ProffessionalTax { get; set; }
        public Nullable<double> Total { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
