//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll_Mvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheet
    {
        public int Id { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<System.DateTime> Complete_Date { get; set; }
        public string WorkhastobeDone { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
